---
title: "Mapas"
author: "Alejandra Arias"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
```

```{r warning=FALSE}
options(scipen = 999)

library("pacman")
p_load(tidyverse,readxl, readr, dplyr,tidyr,writexl,foreign,naniar,plyr, scales,lubridate)

library(ggplot2)
install.packages("leaflet", repos = "http://cran.us.r-project.org")
library(leaflet)
install.packages("remotes", repos = "http://cran.us.r-project.org")
library(remotes)

install_github("r-spatial/sf", force = TRUE)
library(sf)
carpetas2016 <- read_csv("C:/Users/vasq_/OneDrive/EjerciciosR/Mapas/carpetasFGJ_2016.csv")
carpetas2016 <- carpetas2016 %>% select(-c(anio_inicio, fecha_inicio, fecha_hecho, hora_inicio, hora_hecho, mes_inicio, competencia))
carpetas2016 <- carpetas2016 %>% filter(delito=="EXTORSION")
carpetas2016$Total <- ifelse(carpetas2016$delito=="EXTORSION", 1,0)

alcaldia2016 <- carpetas2016 %>% group_by(alcaldia_hecho, longitud, latitud) %>% tally(Total)


alcaldia2016 = alcaldia2016[-c(7,18), ]



poli <- st_read("C:/Users/vasq_/OneDrive/EjerciciosR/Mapas/poligonos_alcaldias_cdmx.shp")

mapabase_16 <- leaflet(alcaldia2016) %>%
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircles(~longitud, ~latitud, weight = 3, radius = 40,stroke = TRUE,
             fillOpacity = 0.8,
             color = "red") %>% 
  setView(lng = -99.12766, lat = 19.42847, zoom = 10) %>% 
  addPolygons(data = poli, color = "blue", stroke = 1, opacity = 0.6,
              highlightOptions = highlightOptions(weight = 5, color = "#666",
                                                  fillOpacity = 0.7,
                                                  bringToFront = TRUE))
mapabase_16

```
#Mapa 2. Cluster de carpetas de Investigación
##Extorsiones en Ciudad de México


```{r warning=FALSE}
cluster16 <- leaflet(alcaldia2016) %>%
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.DarkMatter) %>% 
  addMarkers(lng = ~longitud, lat = ~latitud, clusterOptions = markerClusterOptions())
cluster16

```

